# Generated by Django 4.0.5 on 2022-06-09 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_username_article_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 10, 22, 45, 896871, tzinfo=utc)),
        ),
    ]
