# Generated by Django 4.0.5 on 2022-06-12 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 18, 35, 57, 491355, tzinfo=utc)),
        ),
    ]
