# Generated by Django 4.0.5 on 2022-06-14 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 9, 55, 18, 894848, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:\\Users\\Korisnik\\pero\\myproject\\articles\\media\\media/files')),
                ('format', models.CharField(max_length=255)),
                ('headline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.article')),
            ],
        ),
    ]
