# Generated by Django 4.0.5 on 2022-06-14 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_article_pub_date_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 10, 55, 15, 827346, tzinfo=utc)),
        ),
    ]
