# Generated by Django 4.0.5 on 2022-06-14 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 11, 6, 30, 600860, tzinfo=utc)),
        ),
    ]
