# Generated by Django 4.0.5 on 2022-07-02 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 15, 11, 25, 221991, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
